#!/bin/sh
export NODE_ENV=production
cd /home/root
/home/root/NcpGateway -n 1 -b 115200 -f x -i 0 -o 0 -p /dev/ttyS2 &
#git clone --depth=1 http://dykim@192.168.0.88/smartonoff/production.git
#cd /home/root/production
#nohup node /home/root/production/src/index.js &
